#define MST_CODEC_AC3_AD_PM1_ADDR     0x0780  
#define MST_CODEC_AC3_AD_PM1_SIZE     0x0003  

BYTE code mst_codec_ac3_ad_pm1[]=
{   //PM 1 Addr: 0x0780-0x0BFF[0x0480] Len=0x0471(words)/3411(bytes)
    0x01, 0x01, 0x80, 0x07, 0x53, 0x0D,

    //start:0x000780, len:55(words), 165(bytes)
    0x01, 0x80, 0x07, 
};

#define MST_CODEC_AC3_AD_PM2_ADDR     0x121F  
#define MST_CODEC_AC3_AD_PM2_SIZE     0x0003  

BYTE code mst_codec_ac3_ad_pm2[]=
{   //PM 2 Addr: 0x121F-0x3AC6[0x28A8] Len=0x0A33(words)/7833(bytes)
    0x01, 0x01, 0x1F, 0x12, 0x99, 0x1E,

    //start:0x00121F, len:1(words), 3(bytes)
    0x07, 0x20, 0xDD, 
};

#define MST_CODEC_AC3_AD_PM3_ADDR     0x5800  
#define MST_CODEC_AC3_AD_PM3_SIZE     0x0003  

BYTE code mst_codec_ac3_ad_pm3[]=
{   //PM 3 Addr: 0x5800-0x97FF[0x4000] Len=0x12D1(words)/14451(bytes)
    0x01, 0x01, 0x00, 0x58, 0x73, 0x38,

    //start:0x005800, len:853(words), 2559(bytes)
    0x00, 0x0C, 0x0C, 
};

//Total: [PM1 0x0471/0480 words] [PM2 0x0A33/28A8 words] [PM3 0x12D1/4000 words] [PM4 0x0000/4800 words] 
//Version:[0D.20.07](codec_ac3_ad/D)
//Time: 2009/06/12 16:34:25
//Generated by MStar Audio DSP Pack Utility Ver. 4.33.00 <allan.liang>
