////////////////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
//
// Unless otherwise stipulated in writing, any and all information contained herein
// regardless in any format shall remain the property of MStar Semiconductor Inc.
//
// You can redistribute it and/or modify it under the terms of the GNU General Public
// License version 2 as published by the Free Foundation. This program is distributed
// in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
// implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
/////////////////////////////////////////////////////////////////////////////////////////////

//****************************************************
// TCON Drive Chip           : Titania3_TCON_Driver
// TCON Excel CodeGen Version: 1.04
// TCON Excel SW      Version: 1.00
// TCON Excel update date    : 2009/11/9 11:11
//****************************************************

#ifndef _DRVTCON_TBL_C_
#define _DRVTCON_TBL_C_

//****************************************************
// Init  LG32
//****************************************************
MS_U8 MST_TCON_LG32_Init_TBL[][REG_ADDR_SIZE+REG_MASK_SIZE+TCON_TAB_LG42_Init_NUMS]=
{                 // Reg           Mask  Value
 { DRV_TCON_REG(REG_TC_CLK_GEN_57_L), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_CLK_GEN_57_H), 0xFF, 0x01/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_00_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_00_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_01_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_01_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_02_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_02_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_03_L), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_03_H), 0xFF, 0xE0/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_04_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_04_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_05_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_05_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_06_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_06_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_07_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_07_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_08_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_08_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_09_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_09_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0A_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0A_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0B_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0B_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0C_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0C_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0D_L), 0xFF, 0x01/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0D_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0E_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0E_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0F_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0F_H), 0xFF, 0x70/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_10_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_10_H), 0xFF, 0x70/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_11_L), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_11_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_12_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_12_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_13_L), 0xFF, 0xF6/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_13_H), 0xFF, 0x07/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_14_L), 0xFF, 0xB2/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_14_H), 0xFF, 0x17/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_15_L), 0xFF, 0x2C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_15_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_16_L), 0xFF, 0x64/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_16_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_17_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_17_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_18_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_18_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_19_L), 0xFF, 0x2B/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_19_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1A_L), 0xFF, 0x63/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1A_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1B_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1B_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1C_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1C_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1D_L), 0xFF, 0x2D/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1D_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1E_L), 0xFF, 0x65/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1E_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1F_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1F_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_20_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_20_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_21_L), 0xFF, 0x20/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_21_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_22_L), 0xFF, 0x20/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_22_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_23_L), 0xFF, 0x33/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_23_H), 0xFF, 0x07/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_24_L), 0xFF, 0x3E/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_24_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_25_L), 0xFF, 0x1C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_25_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_26_L), 0xFF, 0x4B/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_26_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_27_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_27_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_28_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_28_H), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_29_L), 0xFF, 0x1D/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_29_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2A_L), 0xFF, 0x4C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2A_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2B_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2B_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2C_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2C_H), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2D_L), 0xFF, 0x1E/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2D_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2E_L), 0xFF, 0x4D/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2E_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2F_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2F_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_30_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_30_H), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_31_L), 0xFF, 0x28/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_31_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_32_L), 0xFF, 0x60/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_32_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_33_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_33_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_34_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_34_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_35_L), 0xFF, 0x29/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_35_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_36_L), 0xFF, 0x61/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_36_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_37_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_37_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_38_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_38_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_39_L), 0xFF, 0xD0/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_39_H), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3A_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3A_H), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3B_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3B_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3C_L), 0xFF, 0x18/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3C_H), 0xFF, 0x18/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3D_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3D_H), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3E_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3E_H), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3F_L), 0xFF, 0x0C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3F_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_40_L), 0xFF, 0x2A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_40_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_41_L), 0xFF, 0x62/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_41_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_42_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_42_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_43_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_43_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_44_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_44_H), 0xFF, 0x70/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_45_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_45_H), 0xFF, 0xF0/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_46_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_46_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_47_L), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_47_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_48_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_48_H), 0xFF, 0x70/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_49_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_49_H), 0xFF, 0xF0/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4A_L), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4A_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4B_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4B_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4C_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4C_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4D_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4D_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4E_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4E_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4F_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4F_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_50_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_50_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_51_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_51_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_52_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_52_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_53_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_53_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_54_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_54_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_55_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_55_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_56_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_56_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_57_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_57_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_58_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_58_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_59_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_59_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5A_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5A_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5B_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5B_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5C_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5C_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5D_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5D_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5E_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5E_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5F_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5F_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_60_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_60_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_H), 0xFF, 0x3F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_62_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_62_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_63_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_63_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_64_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_64_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_65_L), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_65_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_66_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_66_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_67_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_67_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_68_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_68_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_69_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_69_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6A_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6A_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6B_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6B_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6C_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6C_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6D_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6D_H), 0xFF, 0xC0/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6E_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6E_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6F_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6F_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_70_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_70_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_71_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_71_H), 0xFF, 0x30/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_72_L), 0xFF, 0x1E/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_72_H), 0xFF, 0x0E/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_73_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_73_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_74_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_74_H), 0xFF, 0x3F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_75_L), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_75_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_76_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_76_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_77_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_77_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_78_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_78_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_79_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_79_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7A_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7A_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7B_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7B_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7C_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7C_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7D_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7D_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7E_L), 0xFF, 0x1B/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7E_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7F_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7F_H), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TABLE_END)   , 0x00, 0x00,  }
};

//****************************************************
// Init_MOD  LG32
//****************************************************
MS_U8 MST_TCON_LG32_Init_MOD_TBL[][REG_ADDR_SIZE+REG_MASK_SIZE+TCON_TAB_LG42_Init_MOD_NUMS]=
{                 // Reg           Mask  Value
 { DRV_TCON_REG(REG_TC_MOD_BK00_00_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_00_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_20_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_20_H), 0xFF, 0x44/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_30_L), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_30_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_31_L), 0xFF, 0x03/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_31_H), 0xFF, 0x00/*ALL*/, },


 { DRV_TCON_REG(REG_TC_MOD_BK00_33_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_33_H), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_34_L), 0xFF, 0x03/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_34_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_35_L), 0xFF, 0x55/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_35_H), 0xFF, 0x55/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_36_L), 0xFF, 0x55/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_36_H), 0xFF, 0x55/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_37_L), 0xFF, 0x05/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_37_H), 0xFF, 0x00/*ALL*/, },


 { DRV_TCON_REG(REG_TC_MOD_BK00_40_L), 0xFF, 0x0C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_40_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_45_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_45_H), 0xFF, 0x03/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_49_L), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_49_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_4A_L), 0xFF, 0x03/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_4A_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_4B_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_4B_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_53_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_53_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_58_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_58_H), 0xFF, 0x03/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5A_L), 0xFF, 0x30/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5A_H), 0xFF, 0x05/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5C_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5C_H), 0xFF, 0xEC/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5E_L), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5E_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5F_L), 0xFF, 0x60/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5F_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6D_L), 0xFF, 0x55/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6D_H), 0xFF, 0x57/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6E_L), 0xFF, 0x55/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6E_H), 0xFF, 0x5D/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6F_L), 0xFF, 0x05/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6F_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_73_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_73_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_77_L), 0xFF, 0x07/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_77_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_78_L), 0xFF, 0x4C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_78_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_79_L), 0xFF, 0x7F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_79_H), 0xFF, 0xC7/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7A_L), 0xFF, 0x20/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7A_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7C_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7C_H), 0xFF, 0x68/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7D_L), 0xFF, 0x65/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7D_H), 0xFF, 0xA1/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TABLE_END) , 0x00, 0x00 }
};

//****************************************************
// Power_Sequence_On  LG32
//****************************************************
MS_U8 MST_TCON_LG32_Power_Sequence_On_TBL[][REG_ADDR_SIZE+REG_MASK_SIZE+TCON_TAB_LG42_Power_Sequence_On_NUMS]=
{                 // Reg           Mask  Value
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x01, 0x00/*ALL*/,
                                         1/*Delay_Ready*/,
                                         5/*Delay_Time*/,
                                         TCON_SIGNAL_POL/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_H), 0x30, 0x00/*ALL*/,
                                         1/*Delay_Ready*/,
                                         28/*Delay_Time*/,
                                         TCON_SIGNAL_VGH/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x20, 0x00/*ALL*/,
                                         1/*Delay_Ready*/,
                                         30/*Delay_Time*/,
                                         TCON_SIGNAL_SOE/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x02, 0x00/*ALL*/,
                                         1/*Delay_Ready*/,
                                         30/*Delay_Time*/,
                                         TCON_SIGNAL_VST/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x1C, 0x00/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_GCLK/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_H), 0x0E, 0x00/*ALL*/,
                                         1/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_GCLK/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TABLE_END) , 0x00, 0x00, TCON_SIGNAL_NUMS }
};

//****************************************************
// Power_Sequence_Off  LG32
//****************************************************
MS_U8 MST_TCON_LG32_Power_Sequence_Off_TBL[][REG_ADDR_SIZE+REG_MASK_SIZE+TCON_TAB_LG42_Power_Sequence_Off_NUMS]=
{                 // Reg           Mask  Value
 { DRV_TCON_REG(REG_TC_TCON_61_H), 0x0E, 0x0E/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_GCLK/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x1C, 0x1C/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_GCLK/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x02, 0x02/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_VST/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x20, 0x20/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_SOE/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_H), 0x30, 0x30/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_VGH/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x01, 0x01/*ALL*/,
                                         1/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_POL/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TABLE_END) , 0x00, 0x00, TCON_SIGNAL_NUMS }
};



//****************************************************
// Init  LG37
//****************************************************
MS_U8 MST_TCON_LG37_Init_TBL[][REG_ADDR_SIZE+REG_MASK_SIZE+TCON_TAB_LG42_Init_NUMS]=
{                 // Reg           Mask  Value
 { DRV_TCON_REG(REG_TC_CLK_GEN_57_L), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_CLK_GEN_57_H), 0xFF, 0x01/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_00_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_00_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_01_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_01_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_02_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_02_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_03_L), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_03_H), 0xFF, 0xE0/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_04_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_04_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_05_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_05_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_06_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_06_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_07_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_07_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_08_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_08_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_09_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_09_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0A_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0A_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0B_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0B_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0C_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0C_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0D_L), 0xFF, 0x01/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0D_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0E_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0E_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0F_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0F_H), 0xFF, 0x70/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_10_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_10_H), 0xFF, 0x70/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_11_L), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_11_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_12_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_12_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_13_L), 0xFF, 0xF6/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_13_H), 0xFF, 0x07/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_14_L), 0xFF, 0xB2/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_14_H), 0xFF, 0x17/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_15_L), 0xFF, 0x2C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_15_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_16_L), 0xFF, 0x64/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_16_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_17_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_17_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_18_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_18_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_19_L), 0xFF, 0x2B/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_19_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1A_L), 0xFF, 0x63/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1A_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1B_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1B_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1C_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1C_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1D_L), 0xFF, 0x2D/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1D_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1E_L), 0xFF, 0x65/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1E_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1F_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1F_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_20_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_20_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_21_L), 0xFF, 0x20/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_21_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_22_L), 0xFF, 0x20/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_22_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_23_L), 0xFF, 0x33/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_23_H), 0xFF, 0x07/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_24_L), 0xFF, 0x3E/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_24_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_25_L), 0xFF, 0x1C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_25_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_26_L), 0xFF, 0x4B/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_26_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_27_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_27_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_28_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_28_H), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_29_L), 0xFF, 0x1D/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_29_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2A_L), 0xFF, 0x4C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2A_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2B_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2B_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2C_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2C_H), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2D_L), 0xFF, 0x1E/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2D_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2E_L), 0xFF, 0x4D/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2E_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2F_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2F_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_30_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_30_H), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_31_L), 0xFF, 0x28/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_31_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_32_L), 0xFF, 0x60/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_32_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_33_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_33_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_34_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_34_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_35_L), 0xFF, 0x29/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_35_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_36_L), 0xFF, 0x61/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_36_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_37_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_37_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_38_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_38_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_39_L), 0xFF, 0xD0/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_39_H), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3A_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3A_H), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3B_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3B_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3C_L), 0xFF, 0x18/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3C_H), 0xFF, 0x18/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3D_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3D_H), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3E_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3E_H), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3F_L), 0xFF, 0x0C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3F_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_40_L), 0xFF, 0x2A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_40_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_41_L), 0xFF, 0x62/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_41_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_42_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_42_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_43_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_43_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_44_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_44_H), 0xFF, 0x70/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_45_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_45_H), 0xFF, 0xF0/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_46_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_46_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_47_L), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_47_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_48_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_48_H), 0xFF, 0x70/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_49_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_49_H), 0xFF, 0xF0/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4A_L), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4A_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4B_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4B_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4C_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4C_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4D_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4D_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4E_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4E_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4F_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4F_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_50_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_50_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_51_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_51_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_52_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_52_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_53_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_53_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_54_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_54_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_55_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_55_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_56_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_56_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_57_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_57_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_58_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_58_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_59_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_59_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5A_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5A_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5B_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5B_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5C_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5C_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5D_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5D_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5E_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5E_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5F_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5F_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_60_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_60_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_H), 0xFF, 0x3F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_62_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_62_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_63_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_63_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_64_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_64_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_65_L), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_65_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_66_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_66_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_67_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_67_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_68_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_68_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_69_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_69_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6A_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6A_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6B_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6B_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6C_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6C_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6D_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6D_H), 0xFF, 0xC0/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6E_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6E_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6F_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6F_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_70_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_70_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_71_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_71_H), 0xFF, 0x30/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_72_L), 0xFF, 0x1E/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_72_H), 0xFF, 0x0E/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_73_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_73_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_74_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_74_H), 0xFF, 0x3F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_75_L), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_75_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_76_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_76_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_77_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_77_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_78_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_78_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_79_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_79_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7A_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7A_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7B_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7B_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7C_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7C_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7D_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7D_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7E_L), 0xFF, 0x1B/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7E_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7F_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7F_H), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TABLE_END)   , 0x00, 0x00,  }
};

//****************************************************
// Init_MOD  LG37
//****************************************************
MS_U8 MST_TCON_LG37_Init_MOD_TBL[][REG_ADDR_SIZE+REG_MASK_SIZE+TCON_TAB_LG42_Init_MOD_NUMS]=
{                 // Reg           Mask  Value
 { DRV_TCON_REG(REG_TC_MOD_BK00_00_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_00_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_20_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_20_H), 0xFF, 0x44/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_30_L), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_30_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_31_L), 0xFF, 0x03/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_31_H), 0xFF, 0x00/*ALL*/, },

 { DRV_TCON_REG(REG_TC_MOD_BK00_40_L), 0xFF, 0x0C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_40_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_45_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_45_H), 0xFF, 0x03/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_49_L), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_49_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_4A_L), 0xFF, 0x03/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_4A_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_4B_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_4B_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_53_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_53_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_58_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_58_H), 0xFF, 0x03/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5A_L), 0xFF, 0x30/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5A_H), 0xFF, 0x05/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5C_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5C_H), 0xFF, 0xEC/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5E_L), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5E_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5F_L), 0xFF, 0x60/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5F_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6D_L), 0xFF, 0x55/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6D_H), 0xFF, 0x57/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6E_L), 0xFF, 0x55/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6E_H), 0xFF, 0x5D/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6F_L), 0xFF, 0x05/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6F_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_73_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_73_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_77_L), 0xFF, 0x07/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_77_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_78_L), 0xFF, 0x4C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_78_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_79_L), 0xFF, 0x7F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_79_H), 0xFF, 0xC7/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7A_L), 0xFF, 0x20/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7A_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7C_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7C_H), 0xFF, 0x68/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7D_L), 0xFF, 0x65/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7D_H), 0xFF, 0xA1/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TABLE_END) , 0x00, 0x00 }
};

//****************************************************
// Power_Sequence_On  LG37
//****************************************************
MS_U8 MST_TCON_LG37_Power_Sequence_On_TBL[][REG_ADDR_SIZE+REG_MASK_SIZE+TCON_TAB_LG42_Power_Sequence_On_NUMS]=
{                 // Reg           Mask  Value
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x01, 0x00/*ALL*/,
                                         1/*Delay_Ready*/,
                                         5/*Delay_Time*/,
                                         TCON_SIGNAL_POL/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_H), 0x30, 0x00/*ALL*/,
                                         1/*Delay_Ready*/,
                                         28/*Delay_Time*/,
                                         TCON_SIGNAL_VGH/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x20, 0x00/*ALL*/,
                                         1/*Delay_Ready*/,
                                         30/*Delay_Time*/,
                                         TCON_SIGNAL_SOE/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x02, 0x00/*ALL*/,
                                         1/*Delay_Ready*/,
                                         30/*Delay_Time*/,
                                         TCON_SIGNAL_VST/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x1C, 0x00/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_GCLK/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_H), 0x0E, 0x00/*ALL*/,
                                         1/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_GCLK/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TABLE_END) , 0x00, 0x00, TCON_SIGNAL_NUMS }
};

//****************************************************
// Power_Sequence_Off  LG37
//****************************************************
MS_U8 MST_TCON_LG37_Power_Sequence_Off_TBL[][REG_ADDR_SIZE+REG_MASK_SIZE+TCON_TAB_LG42_Power_Sequence_Off_NUMS]=
{                 // Reg           Mask  Value
 { DRV_TCON_REG(REG_TC_TCON_61_H), 0x0E, 0x0E/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_GCLK/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x1C, 0x1C/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_GCLK/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x02, 0x02/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_VST/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x20, 0x20/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_SOE/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_H), 0x30, 0x30/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_VGH/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x01, 0x01/*ALL*/,
                                         1/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_POL/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TABLE_END) , 0x00, 0x00, TCON_SIGNAL_NUMS }
};


//****************************************************
// Init  LG42
//****************************************************
MS_U8 MST_TCON_LG42_Init_TBL[][REG_ADDR_SIZE+REG_MASK_SIZE+TCON_TAB_LG42_Init_NUMS]=
{                 // Reg           Mask  Value
 { DRV_TCON_REG(REG_TC_CLK_GEN_57_L), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_CLK_GEN_57_H), 0xFF, 0x01/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_00_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_00_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_01_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_01_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_02_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_02_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_03_L), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_03_H), 0xFF, 0xE0/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_04_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_04_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_05_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_05_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_06_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_06_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_07_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_07_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_08_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_08_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_09_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_09_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0A_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0A_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0B_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0B_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0C_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0C_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0D_L), 0xFF, 0x01/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0D_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0E_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0E_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0F_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0F_H), 0xFF, 0x70/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_10_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_10_H), 0xFF, 0x70/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_11_L), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_11_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_12_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_12_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_13_L), 0xFF, 0xF6/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_13_H), 0xFF, 0x07/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_14_L), 0xFF, 0xB2/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_14_H), 0xFF, 0x17/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_15_L), 0xFF, 0x2C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_15_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_16_L), 0xFF, 0x64/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_16_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_17_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_17_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_18_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_18_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_19_L), 0xFF, 0x2B/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_19_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1A_L), 0xFF, 0x63/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1A_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1B_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1B_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1C_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1C_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1D_L), 0xFF, 0x2D/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1D_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1E_L), 0xFF, 0x65/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1E_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1F_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1F_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_20_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_20_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_21_L), 0xFF, 0x20/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_21_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_22_L), 0xFF, 0x20/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_22_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_23_L), 0xFF, 0x33/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_23_H), 0xFF, 0x07/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_24_L), 0xFF, 0x3E/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_24_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_25_L), 0xFF, 0x1C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_25_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_26_L), 0xFF, 0x4B/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_26_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_27_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_27_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_28_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_28_H), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_29_L), 0xFF, 0x1D/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_29_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2A_L), 0xFF, 0x4C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2A_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2B_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2B_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2C_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2C_H), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2D_L), 0xFF, 0x1E/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2D_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2E_L), 0xFF, 0x4D/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2E_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2F_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2F_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_30_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_30_H), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_31_L), 0xFF, 0x28/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_31_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_32_L), 0xFF, 0x60/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_32_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_33_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_33_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_34_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_34_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_35_L), 0xFF, 0x29/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_35_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_36_L), 0xFF, 0x61/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_36_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_37_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_37_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_38_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_38_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_39_L), 0xFF, 0xD0/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_39_H), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3A_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3A_H), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3B_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3B_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3C_L), 0xFF, 0x18/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3C_H), 0xFF, 0x18/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3D_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3D_H), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3E_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3E_H), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3F_L), 0xFF, 0x0C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3F_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_40_L), 0xFF, 0x2A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_40_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_41_L), 0xFF, 0x62/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_41_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_42_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_42_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_43_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_43_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_44_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_44_H), 0xFF, 0x70/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_45_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_45_H), 0xFF, 0xF0/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_46_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_46_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_47_L), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_47_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_48_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_48_H), 0xFF, 0x70/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_49_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_49_H), 0xFF, 0xF0/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4A_L), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4A_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4B_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4B_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4C_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4C_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4D_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4D_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4E_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4E_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4F_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4F_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_50_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_50_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_51_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_51_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_52_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_52_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_53_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_53_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_54_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_54_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_55_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_55_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_56_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_56_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_57_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_57_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_58_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_58_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_59_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_59_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5A_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5A_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5B_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5B_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5C_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5C_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5D_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5D_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5E_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5E_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5F_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5F_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_60_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_60_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_H), 0xFF, 0x3F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_62_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_62_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_63_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_63_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_64_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_64_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_65_L), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_65_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_66_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_66_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_67_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_67_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_68_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_68_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_69_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_69_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6A_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6A_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6B_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6B_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6C_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6C_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6D_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6D_H), 0xFF, 0xC0/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6E_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6E_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6F_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6F_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_70_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_70_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_71_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_71_H), 0xFF, 0x30/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_72_L), 0xFF, 0x1E/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_72_H), 0xFF, 0x0E/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_73_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_73_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_74_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_74_H), 0xFF, 0x3F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_75_L), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_75_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_76_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_76_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_77_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_77_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_78_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_78_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_79_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_79_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7A_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7A_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7B_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7B_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7C_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7C_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7D_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7D_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7E_L), 0xFF, 0x1B/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7E_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7F_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7F_H), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TABLE_END)   , 0x00, 0x00,  }
};

//****************************************************
// Init_MOD  LG42
//****************************************************
MS_U8 MST_TCON_LG42_Init_MOD_TBL[][REG_ADDR_SIZE+REG_MASK_SIZE+TCON_TAB_LG42_Init_MOD_NUMS]=
{                 // Reg           Mask  Value
 { DRV_TCON_REG(REG_TC_MOD_BK00_00_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_00_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_20_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_20_H), 0xFF, 0x44/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_30_L), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_30_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_31_L), 0xFF, 0x03/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_31_H), 0xFF, 0x00/*ALL*/, },

 { DRV_TCON_REG(REG_TC_MOD_BK00_40_L), 0xFF, 0x0C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_40_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_45_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_45_H), 0xFF, 0x03/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_49_L), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_49_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_4A_L), 0xFF, 0x03/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_4A_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_4B_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_4B_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_53_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_53_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_58_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_58_H), 0xFF, 0x03/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5A_L), 0xFF, 0x30/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5A_H), 0xFF, 0x05/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5C_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5C_H), 0xFF, 0xEC/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5E_L), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5E_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5F_L), 0xFF, 0x60/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5F_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6D_L), 0xFF, 0x55/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6D_H), 0xFF, 0x57/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6E_L), 0xFF, 0x55/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6E_H), 0xFF, 0x5D/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6F_L), 0xFF, 0x05/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6F_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_73_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_73_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_77_L), 0xFF, 0x07/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_77_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_78_L), 0xFF, 0x4C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_78_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_79_L), 0xFF, 0x7F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_79_H), 0xFF, 0xC7/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7A_L), 0xFF, 0x20/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7A_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7C_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7C_H), 0xFF, 0x68/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7D_L), 0xFF, 0x65/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7D_H), 0xFF, 0xA1/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TABLE_END) , 0x00, 0x00 }
};

//****************************************************
// Power_Sequence_On  LG42
//****************************************************
MS_U8 MST_TCON_LG42_Power_Sequence_On_TBL[][REG_ADDR_SIZE+REG_MASK_SIZE+TCON_TAB_LG42_Power_Sequence_On_NUMS]=
{                 // Reg           Mask  Value
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x01, 0x00/*ALL*/,
                                         1/*Delay_Ready*/,
                                         5/*Delay_Time*/,
                                         TCON_SIGNAL_POL/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_H), 0x30, 0x00/*ALL*/,
                                         1/*Delay_Ready*/,
                                         28/*Delay_Time*/,
                                         TCON_SIGNAL_VGH/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x20, 0x00/*ALL*/,
                                         1/*Delay_Ready*/,
                                         30/*Delay_Time*/,
                                         TCON_SIGNAL_SOE/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x02, 0x00/*ALL*/,
                                         1/*Delay_Ready*/,
                                         30/*Delay_Time*/,
                                         TCON_SIGNAL_VST/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x1C, 0x00/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_GCLK/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_H), 0x0E, 0x00/*ALL*/,
                                         1/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_GCLK/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TABLE_END) , 0x00, 0x00, TCON_SIGNAL_NUMS }
};

//****************************************************
// Power_Sequence_Off  LG42
//****************************************************
MS_U8 MST_TCON_LG42_Power_Sequence_Off_TBL[][REG_ADDR_SIZE+REG_MASK_SIZE+TCON_TAB_LG42_Power_Sequence_Off_NUMS]=
{                 // Reg           Mask  Value
 { DRV_TCON_REG(REG_TC_TCON_61_H), 0x0E, 0x0E/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_GCLK/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x1C, 0x1C/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_GCLK/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x02, 0x02/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_VST/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x20, 0x20/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_SOE/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_H), 0x30, 0x30/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_VGH/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x01, 0x01/*ALL*/,
                                         1/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_POL/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TABLE_END) , 0x00, 0x00, TCON_SIGNAL_NUMS }
};


//****************************************************
// Init  LG47
//****************************************************
MS_U8 MST_TCON_LG47_Init_TBL[][REG_ADDR_SIZE+REG_MASK_SIZE+TCON_TAB_LG47_Init_NUMS]=
{                 // Reg           Mask  Value
 { DRV_TCON_REG(REG_TC_CLK_GEN_57_L), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_CLK_GEN_57_H), 0xFF, 0x01/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_00_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_00_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_01_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_01_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_02_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_02_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_03_L), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_03_H), 0xFF, 0xE0/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_04_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_04_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_05_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_05_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_06_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_06_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_07_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_07_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_08_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_08_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_09_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_09_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0A_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0A_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0B_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0B_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0C_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0C_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0D_L), 0xFF, 0x01/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0D_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0E_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0E_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0F_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_0F_H), 0xFF, 0x70/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_10_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_10_H), 0xFF, 0x70/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_11_L), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_11_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_12_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_12_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_13_L), 0xFF, 0xF6/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_13_H), 0xFF, 0x07/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_14_L), 0xFF, 0xB2/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_14_H), 0xFF, 0x17/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_15_L), 0xFF, 0x2C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_15_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_16_L), 0xFF, 0x64/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_16_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_17_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_17_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_18_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_18_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_19_L), 0xFF, 0x2B/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_19_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1A_L), 0xFF, 0x63/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1A_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1B_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1B_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1C_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1C_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1D_L), 0xFF, 0x2D/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1D_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1E_L), 0xFF, 0x65/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1E_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1F_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_1F_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_20_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_20_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_21_L), 0xFF, 0x20/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_21_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_22_L), 0xFF, 0x20/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_22_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_23_L), 0xFF, 0x33/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_23_H), 0xFF, 0x07/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_24_L), 0xFF, 0x36/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_24_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_25_L), 0xFF, 0x1C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_25_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_26_L), 0xFF, 0x4B/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_26_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_27_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_27_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_28_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_28_H), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_29_L), 0xFF, 0x1D/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_29_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2A_L), 0xFF, 0x4C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2A_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2B_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2B_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2C_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2C_H), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2D_L), 0xFF, 0x1E/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2D_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2E_L), 0xFF, 0x4D/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2E_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2F_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_2F_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_30_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_30_H), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_31_L), 0xFF, 0x28/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_31_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_32_L), 0xFF, 0x60/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_32_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_33_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_33_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_34_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_34_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_35_L), 0xFF, 0x29/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_35_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_36_L), 0xFF, 0x61/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_36_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_37_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_37_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_38_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_38_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_39_L), 0xFF, 0xD0/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_39_H), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3A_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3A_H), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3B_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3B_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3C_L), 0xFF, 0x18/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3C_H), 0xFF, 0x18/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3D_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3D_H), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3E_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3E_H), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3F_L), 0xFF, 0x0C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_3F_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_40_L), 0xFF, 0x2A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_40_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_41_L), 0xFF, 0x62/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_41_H), 0xFF, 0x04/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_42_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_42_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_43_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_43_H), 0xFF, 0x26/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_44_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_44_H), 0xFF, 0x70/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_45_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_45_H), 0xFF, 0xF0/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_46_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_46_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_47_L), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_47_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_48_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_48_H), 0xFF, 0x70/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_49_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_49_H), 0xFF, 0xF0/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4A_L), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4A_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4B_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4B_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4C_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4C_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4D_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4D_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4E_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4E_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4F_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_4F_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_50_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_50_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_51_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_51_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_52_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_52_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_53_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_53_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_54_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_54_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_55_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_55_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_56_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_56_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_57_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_57_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_58_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_58_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_59_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_59_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5A_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5A_H), 0xFF, 0x0F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5B_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5B_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5C_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5C_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5D_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5D_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5E_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5E_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5F_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_5F_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_60_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_60_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_H), 0xFF, 0x3F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_62_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_62_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_63_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_63_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_64_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_64_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_65_L), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_65_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_66_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_66_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_67_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_67_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_68_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_68_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_69_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_69_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6A_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6A_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6B_L), 0xFF, 0x5A/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6B_H), 0xFF, 0x08/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6C_L), 0xFF, 0x19/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6C_H), 0xFF, 0x06/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6D_L), 0xFF, 0x40/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6D_H), 0xFF, 0xC0/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6E_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6E_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6F_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_6F_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_70_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_70_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_71_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_71_H), 0xFF, 0x30/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_72_L), 0xFF, 0x1E/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_72_H), 0xFF, 0x0E/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_73_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_73_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_74_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_74_H), 0xFF, 0x3F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_75_L), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_75_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_76_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_76_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_77_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_77_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_78_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_78_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_79_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_79_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7A_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7A_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7B_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7B_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7C_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7C_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7D_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7D_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7E_L), 0xFF, 0x1B/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7E_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7F_L), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TC_TCON_7F_H), 0xFF, 0xFF/*ALL*/, },
 { DRV_TCON_REG(REG_TABLE_END)   , 0x00, 0x00,  }
};

//****************************************************
// Init_MOD  LG47
//****************************************************
MS_U8 MST_TCON_LG47_Init_MOD_TBL[][REG_ADDR_SIZE+REG_MASK_SIZE+TCON_TAB_LG47_Init_MOD_NUMS]=
{                 // Reg           Mask  Value
 { DRV_TCON_REG(REG_TC_MOD_BK00_00_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_00_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_20_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_20_H), 0xFF, 0x44/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_30_L), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_30_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_31_L), 0xFF, 0x03/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_31_H), 0xFF, 0x00/*ALL*/, },

 { DRV_TCON_REG(REG_TC_MOD_BK00_40_L), 0xFF, 0x0C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_40_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_45_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_45_H), 0xFF, 0x03/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_49_L), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_49_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_4A_L), 0xFF, 0x03/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_4A_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_4B_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_4B_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_53_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_53_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_58_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_58_H), 0xFF, 0x03/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5A_L), 0xFF, 0x30/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5A_H), 0xFF, 0x05/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5C_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5C_H), 0xFF, 0xEC/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5E_L), 0xFF, 0x02/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5E_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5F_L), 0xFF, 0x60/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_5F_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6D_L), 0xFF, 0x55/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6D_H), 0xFF, 0x57/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6E_L), 0xFF, 0x55/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6E_H), 0xFF, 0x5D/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6F_L), 0xFF, 0x05/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_6F_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_73_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_73_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_77_L), 0xFF, 0x07/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_77_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_78_L), 0xFF, 0x4C/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_78_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_79_L), 0xFF, 0x7F/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_79_H), 0xFF, 0xC7/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7A_L), 0xFF, 0x20/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7A_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7C_L), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7C_H), 0xFF, 0x68/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7D_L), 0xFF, 0x65/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_7D_H), 0xFF, 0xA1/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x00/*ALL*/, },
 { DRV_TCON_REG(REG_TC_MOD_BK00_42_H), 0xFF, 0x10/*ALL*/, },
 { DRV_TCON_REG(REG_TABLE_END) , 0x00, 0x00 }
};

//****************************************************
// Power_Sequence_On  LG47
//****************************************************
MS_U8 MST_TCON_LG47_Power_Sequence_On_TBL[][REG_ADDR_SIZE+REG_MASK_SIZE+TCON_TAB_LG47_Power_Sequence_On_NUMS]=
{                 // Reg           Mask  Value
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x01, 0x00/*ALL*/,
                                         1/*Delay_Ready*/,
                                         5/*Delay_Time*/,
                                         TCON_SIGNAL_POL/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_H), 0x30, 0x00/*ALL*/,
                                         1/*Delay_Ready*/,
                                         28/*Delay_Time*/,
                                         TCON_SIGNAL_VGH/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x20, 0x00/*ALL*/,
                                         1/*Delay_Ready*/,
                                         30/*Delay_Time*/,
                                         TCON_SIGNAL_SOE/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x02, 0x00/*ALL*/,
                                         1/*Delay_Ready*/,
                                         30/*Delay_Time*/,
                                         TCON_SIGNAL_VST/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x1C, 0x00/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_GCLK/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_H), 0x0E, 0x00/*ALL*/,
                                         1/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_GCLK/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TABLE_END) , 0x00, 0x00, TCON_SIGNAL_NUMS }
};

//****************************************************
// Power_Sequence_Off  LG47
//****************************************************
MS_U8 MST_TCON_LG47_Power_Sequence_Off_TBL[][REG_ADDR_SIZE+REG_MASK_SIZE+TCON_TAB_LG47_Power_Sequence_Off_NUMS]=
{                 // Reg           Mask  Value
 { DRV_TCON_REG(REG_TC_TCON_61_H), 0x0E, 0x0E/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_GCLK/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x1C, 0x1C/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_GCLK/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x02, 0x02/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_VST/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x20, 0x20/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_SOE/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_H), 0x30, 0x30/*ALL*/,
                                         0/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_VGH/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TC_TCON_61_L), 0x01, 0x01/*ALL*/,
                                         1/*Delay_Ready*/,
                                         0/*Delay_Time*/,
                                         TCON_SIGNAL_POL/*Signal_Type*/, },
 { DRV_TCON_REG(REG_TABLE_END) , 0x00, 0x00, TCON_SIGNAL_NUMS }
};

TCON_TAB_INFO TConMAP_Main[TCON_PANEL_NUMS]=
{
	{
	*MST_TCON_LG32_Init_TBL, TCON_TABTYPE_GENERAL,
	*MST_TCON_LG32_Init_MOD_TBL, TCON_TABTYPE_MOD,
	*MST_TCON_LG32_Power_Sequence_On_TBL, TCON_TABTYPE_POWER_SEQUENCE_ON,
	*MST_TCON_LG32_Power_Sequence_Off_TBL, TCON_TABTYPE_POWER_SEQUENCE_OFF,
	},

	{
	*MST_TCON_LG37_Init_TBL, TCON_TABTYPE_GENERAL,
	*MST_TCON_LG37_Init_MOD_TBL, TCON_TABTYPE_MOD,
	*MST_TCON_LG37_Power_Sequence_On_TBL, TCON_TABTYPE_POWER_SEQUENCE_ON,
	*MST_TCON_LG37_Power_Sequence_Off_TBL, TCON_TABTYPE_POWER_SEQUENCE_OFF,
	},


	{
	*MST_TCON_LG42_Init_TBL, TCON_TABTYPE_GENERAL,
	*MST_TCON_LG42_Init_MOD_TBL, TCON_TABTYPE_MOD,
	*MST_TCON_LG42_Power_Sequence_On_TBL, TCON_TABTYPE_POWER_SEQUENCE_ON,
	*MST_TCON_LG42_Power_Sequence_Off_TBL, TCON_TABTYPE_POWER_SEQUENCE_OFF,
	},

	{
	*MST_TCON_LG47_Init_TBL, TCON_TABTYPE_GENERAL,
	*MST_TCON_LG47_Init_MOD_TBL, TCON_TABTYPE_MOD,
	*MST_TCON_LG47_Power_Sequence_On_TBL, TCON_TABTYPE_POWER_SEQUENCE_ON,
	*MST_TCON_LG47_Power_Sequence_Off_TBL, TCON_TABTYPE_POWER_SEQUENCE_OFF,
	},
};

#endif
