#
# Makefile for stand alone kernel driver module by dhjung LGE
#

CONFIG_MSTAR_CHIP_NAME			:= titania3

# Not yet included
#CONFIG_MSTAR_MIU				:= m
#CONFIG_MSTAR_8051				:= m
#CONFIG_MSTAR_AEON				:= m
#CONFIG_MSTAR_RLD				:= m
#CONFIG_MSTAR_MLINK				:= m
#CONFIG_MSTAR_FBDEV				:= m
#CONFIG_MSTAR_AVS				:= m
#CONFIG_MSTAR_MFC				:= m

# Already Kernel Embeded
#CONFIG_MSTAR_NAND				:= m
#CONFIG_MSTAR_IIC				:= m
#CONFIG_MSTAR_GPIO				:= m
#CONFIG_MSTAR_MICOM				:= m
#CONFIG_MSTAR_EMAC				:= m

# Will be module type kernel driver
CONFIG_MSTAR_TSP				:= m
CONFIG_MSTAR_GE					:= m
CONFIG_MSTAR_GOP				:= m
CONFIG_MSTAR_MPOOL				:= m
CONFIG_MSTAR_PWM				:= m
CONFIG_MSTAR_SYSTEM				:= m
CONFIG_MSTAR_SCALER				:= m
CONFIG_MSTAR_MAD				:= m
CONFIG_MSTAR_VD					:= m
CONFIG_MSTAR_MVOP				:= m
CONFIG_MSTAR_MVD				:= m
CONFIG_MSTAR_H264				:= m
CONFIG_MSTAR_IR					:= m
CONFIG_MSTAR_CI					:= m
CONFIG_MSTAR_TTX				:= m
CONFIG_MSTAR_VE 				:= m
CONFIG_MSTAR_CC					:= m
CONFIG_MSTAR_JPEG				:= m
CONFIG_MSTAR_MSMAILBOX			:= m
CONFIG_MSTAR_SPI				:= m
#CONFIG_MSTAR_STR				:= m
CONFIG_MSTAR_M4VE				:= m
CONFIG_MSTAR_DIP				:= m
CONFIG_MSTAR_DEMOD				:= m
CONFIG_MSTAR_MPIF				:= m
CONFIG_MSTAR_AESDMA				:= m
CONFIG_MSTAR_BDMA			    := m
CONFIG_MSTAR_CEC				:= m
CONFIG_MSTAR_PWS				:= m
#CONFIG_MSTAR_LOGO			    := m

export CONFIG_MSTAR_MIU
export CONFIG_MSTAR_8051
export CONFIG_MSTAR_AEON
export CONFIG_MSTAR_RLD
export CONFIG_MSTAR_MLINK
export CONFIG_MSTAR_NAND
export CONFIG_MSTAR_FBDEV
export CONFIG_MSTAR_AVS
export CONFIG_MSTAR_IIC
export CONFIG_MSTAR_GPIO
export CONFIG_MSTAR_MICOM
export CONFIG_MSTAR_TSP
export CONFIG_MSTAR_GE
export CONFIG_MSTAR_GOP
export CONFIG_MSTAR_MPOOL
export CONFIG_MSTAR_PWM
export CONFIG_MSTAR_EMAC
export CONFIG_MSTAR_SYSTEM
export CONFIG_MSTAR_SCALER
export CONFIG_MSTAR_MAD
export CONFIG_MSTAR_VD
export CONFIG_MSTAR_MVOP
export CONFIG_MSTAR_MVD
export CONFIG_MSTAR_H264
export CONFIG_MSTAR_IR
export CONFIG_MSTAR_CI
export CONFIG_MSTAR_TTX
export CONFIG_MSTAR_VE
export CONFIG_MSTAR_CC
export CONFIG_MSTAR_JPEG
export CONFIG_MSTAR_MSMAILBOX
export CONFIG_MSTAR_SPI
export CONFIG_MSTAR_STR
export CONFIG_MSTAR_M4VE
export CONFIG_MSTAR_DIP
export CONFIG_MSTAR_DEMOD
export CONFIG_MSTAR_MFC
export CONFIG_MSTAR_MPIF
export CONFIG_MSTAR_CHIP_NAME
export CONFIG_MSTAR_AESDMA
export CONFIG_MSTAR_BDMA
export CONFIG_MSTAR_CEC
export CONFIG_MSTAR_PWS
export CONFIG_MSTAR_LOGO
