#define MST_DVB_AC3_PM1_ADDR     0x0200  
#define MST_DVB_AC3_PM1_SIZE     0x0003  

BYTE code mst_dvb_ac3_pm1[]=
{   //PM 1 Addr: 0x0200-0x0FEF[0x0DF0] Len=0x0851(words)/6387(bytes)
    0x01, 0x01, 0x00, 0x02, 0xF3, 0x18,

    //start:0x000200, len:70(words), 210(bytes)
    0xEF, 0x83, 0x1C, 

};

#define MST_DVB_AC3_PM2_ADDR     0x0FFF  
#define MST_DVB_AC3_PM2_SIZE     0x0003  

BYTE code mst_dvb_ac3_pm2[]=
{   //PM 2 Addr: 0x0FFF-0x3FFE[0x3000] Len=0x13B1(words)/15123(bytes)
    0x01, 0x01, 0xFF, 0x0F, 0x13, 0x3B,

    //start:0x000FFF, len:1(words), 3(bytes)
    0x6D, 0x10, 0xDD, 
};

#define MST_DVB_AC3_PM3_ADDR     0x4C00  
#define MST_DVB_AC3_PM3_SIZE     0x0003  

BYTE code mst_dvb_ac3_pm3[]=
{   //PM 3 Addr: 0x4C00-0xB7FF[0x6C00] Len=0x0F31(words)/11667(bytes)
    0x01, 0x01, 0x00, 0x4C, 0x93, 0x2D,

    //start:0x004C00, len:872(words), 2616(bytes)
    0x00, 0x0C, 0x0C, 
};

//Total: [PM1 0x0851/0DF0 words] [PM2 0x13B1/3000 words] [PM3 0x0F31/6C00 words] [PM4 0x0000/6000 words] 
//Zero padding Addr:0x001AC1, len=1416
//Zero padding Addr:0x002127, len=6
//Version:[0D.10.6D](dvb_ac3/D)
//Time: 2009/06/12 16:39:53
//Generated by MStar Audio DSP Pack Utility Ver. 4.33.00 <allan.liang>
