#define MST_DVB_DEC_PM1_ADDR     0x0200  
#define MST_DVB_DEC_PM1_SIZE     0x0006  

BYTE code mst_dvb_dec_pm1[]=
{   //PM 1 Addr: 0x0200-0x0DFF[0x0C00] Len=0x0002(words)/6(bytes)
    0x01, 0x01, 0x00, 0x02, 0x06, 0x00,

    //start:0x000200, len:2(words), 6(bytes)
    0x00, 0x00, 0x00, 0x0F, 0x00, 0x0A, 

};

#define MST_DVB_DEC_PM2_ADDR     0x0FFF  
#define MST_DVB_DEC_PM2_SIZE     0x0003  

BYTE code mst_dvb_dec_pm2[]=
{   //PM 2 Addr: 0x0FFF-0x37FE[0x2800] Len=0x0001(words)/3(bytes)
    0x01, 0x01, 0xFF, 0x0F, 0x03, 0x00,

    //start:0x000FFF, len:1(words), 3(bytes)
    0x56, 0x34, 0x12, 

};

#define MST_DVB_DEC_PM3_ADDR     0x8600  
#define MST_DVB_DEC_PM3_SIZE     0x0006  

BYTE code mst_dvb_dec_pm3[]=
{   //PM 3 Addr: 0x8600-0x115FF[0x9000] Len=0x0002(words)/6(bytes)
    0x01, 0x01, 0x00, 0x86, 0x06, 0x00,

    //start:0x008600, len:2(words), 6(bytes)
    0x00, 0x00, 0x00, 0x0F, 0x00, 0x0A, 

};

//Total: [PM1 0x0002/0C00 words] [PM2 0x0001/2800 words] [PM3 0x0002/9000 words] [PM4 0x0000/8000 words] 
//Version:[12.34.56](dvb_dec)
//Time: 2009/11/10 15:09:02
//Generated by MStar Audio DSP Pack Utility Ver. 4.45.00 <burt.lien>
