////////////////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
//
// Unless otherwise stipulated in writing, any and all information contained herein
// regardless in any format shall remain the property of MStar Semiconductor Inc.
//
// You can redistribute it and/or modify it under the terms of the GNU General Public
// License version 2 as published by the Free Foundation. This program is distributed
// in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
// implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
/////////////////////////////////////////////////////////////////////////////////////////////

/* Use 'a' as magic number */
#define MAD_IOC_MAGIC           'a'

#define MDrv_MAD_IOC                    _IO(MAD_IOC_MAGIC, 0)
#define MDrv_MAD_IOCREAD                _IOR(MAD_IOC_MAGIC, 1, int)
#define MDrv_MAD_IOCWRITE               _IOW(MAD_IOC_MAGIC, 2, int)
#define MDrv_MAD_IOCRW                  _IOWR(MAD_IOC_MAGIC, 3, int)
#define MDrv_MAD_AUDIO_INIT             _IO(MAD_IOC_MAGIC, 4)
#define MDrv_MAD_SETNORMALPATH          _IO(MAD_IOC_MAGIC, 5)
#define MDrv_MAD_SET_POWER_OFF         _IOW(MAD_IOC_MAGIC, 6,int)
#define MDrv_MAD_RESET_MAD              _IO(MAD_IOC_MAGIC, 7)
#define MDrv_MAD_PIO8_DEC                   _IO(MAD_IOC_MAGIC, 8)
#define MDrv_MAD_SAMPLING_RATE          _IOR(MAD_IOC_MAGIC, 9, int)
#define MDrv_MAD_RD_MAILBOX             _IOWR(MAD_IOC_MAGIC, 10, int)
#define MDrv_MAD_WR_MAILBOX             _IOW(MAD_IOC_MAGIC, 11, int)
#define MDrv_MAD_DVB_GETSOUNDMODE       _IOR(MAD_IOC_MAGIC, 12,int)
#define MDrv_MAD_DVB_SETSOUNDMODE       _IOW(MAD_IOC_MAGIC, 13,int)
#define MDrv_MAD_DVB_SETSYSTEM          _IOW(MAD_IOC_MAGIC, 14, int)
#define MDrv_MAD_DVB_SETDECCMD          _IOW(MAD_IOC_MAGIC, 15, int)
#define MDrv_MAD_SET_DACOUT_MUTE        _IOW(MAD_IOC_MAGIC, 16,int)
#define MDrv_MAD_SET_VOLUME     	    _IOW(MAD_IOC_MAGIC, 17, int)
#define MDrv_MAD_PROCESS_SETBALANCE     _IOW(MAD_IOC_MAGIC, 18, int)
#define MDrv_MAD_PROCESS_SETBASS        _IOW(MAD_IOC_MAGIC, 19, int)
#define MDrv_MAD_PROCESS_SETTREBLE      _IOW(MAD_IOC_MAGIC, 20, int)
#define MDrv_MAD_PROCESS_SETBBE      _IOW(MAD_IOC_MAGIC, 21, int)
#define MDrv_MAD_PROCESS_SETSRS      _IOW(MAD_IOC_MAGIC, 22, int)
#define MDrv_MAD_PROCESS_SETEQUALIZER_LEVEL            _IOW(MAD_IOC_MAGIC, 23, int)
#define MDrv_MAD_GET_DECODING_TYPE	 	_IOR(MAD_IOC_MAGIC, 24, int)
#define MDrv_MAD_VER_PCM_OUT_INIT       _IO(MAD_IOC_MAGIC, 25)
#define MDrv_MAD_VER_PCM_OUT_PLAY       _IO(MAD_IOC_MAGIC, 26)
#define MDrv_MAD_RD_REG             _IOWR(MAD_IOC_MAGIC, 27, int)
#define MDrv_MAD_WR_REG             _IOW(MAD_IOC_MAGIC, 28, int)
#define MDrv_MAD_SET_BUFFER_INFO        _IOW(MAD_IOC_MAGIC, 29, AUDIO_BUFFER_INFO)
#define MDrv_MAD_START_DECODING				_IOW(MAD_IOC_MAGIC, 30, int)
#define MDrv_MAD_STOP_DECODING				_IO(MAD_IOC_MAGIC, 31)
#define MDrv_MAD_GET_CUR_ANALOG_MODE			_IOWR(MAD_IOC_MAGIC,32, int)
#define MDrv_MAD_SET_USER_ANALOG_MODE		_IOW(MAD_IOC_MAGIC, 33, int)
#define MDrv_MAD_SET_AUTO_VOLUME_CONTROL 		_IOW(MAD_IOC_MAGIC, 34, int)
#define MDrv_MAD_GET_BTSC_A2_STEREO_LEVEL		_IOR(MAD_IOC_MAGIC,35, int)
#define MDrv_MAD_SIF_SETSYSTEM          _IOW(MAD_IOC_MAGIC, 36, U8)
#define MDrv_MAD_INITIALIZE_MODULE		_IOW(MAD_IOC_MAGIC, 37, int)
#define MDrv_MAD_AMPLIFIER_ON          _IO(MAD_IOC_MAGIC, 38)
#define MDrv_MAD_AMPLIFIER_OFF          _IO(MAD_IOC_MAGIC, 39)
#define MDrv_MAD_SET_SPDIF_MUTE                                             _IOW(MAD_IOC_MAGIC, 40, int)
#define MDrv_MAD_SET_SPDIF_OUTPUT_TYPE                                      _IOW(MAD_IOC_MAGIC, 41, int)
#define MDrv_MAD_SET_ADUIO_PLLS_FREQ                                        _IOW(MAD_IOC_MAGIC, 42, int)
#define MDrv_MAD_SET_PCM_DELAY_TIME                                         _IOW(MAD_IOC_MAGIC, 43, int)
#define MDrv_MAD_GET_HDMI_AUDIO_MODE                                        _IOR(MAD_IOC_MAGIC, 44, int)
#define MDrv_MAD_GET_ADEC_STATUS                                            _IOW(MAD_IOC_MAGIC, 45, int)
#define MDrv_MAD_SET_AD_MIXMODE                                              _IOW(MAD_IOC_MAGIC, 46, int)
#define MDrv_MAD_SET_AD_OUTPUTMODE                                         _IOW(MAD_IOC_MAGIC, 47, int)
#define MDrv_MAD_SET_AD_VOLUME                                              _IOW(MAD_IOC_MAGIC, 48, int)
#define MDrv_MAD_SET_HP_OUTPUT_TYPE                                         _IOW(MAD_IOC_MAGIC, 49, int)
#define MDrv_MAD_SET_BTSC_A2_THRESHOLD_LEVEL                        _IOW(MAD_IOC_MAGIC, 50, int)
#define MDrv_MAD_SET_SPKOUT_MODE                                            _IOW(MAD_IOC_MAGIC, 51, int)
#define MDrv_MAD_SIF_ENABLE_DACOUT                                          _IOW(MAD_IOC_MAGIC, 52, int)
#define MDrv_MAD_SIF_GET_BAND_DETECT                                        _IOWR(MAD_IOC_MAGIC, 53, BAND_DETECT_INFO_T)
#define MDrv_MAD_SIF_SET_BAND_SETUP                                         _IOW(MAD_IOC_MAGIC, 54, int)
#define MDrv_MAD_SIF_SET_MODE_SETUP                                         _IOW(MAD_IOC_MAGIC, 55, int)
#define MDrv_MAD_SIF_CHECK_NICAM_DIGITAL                                    _IOW(MAD_IOC_MAGIC, 56, int)
#define MDrv_MAD_SIF_CHECK_AVAILABLE_SYSTEM                                 _IOWR(MAD_IOC_MAGIC, 57, AVAILABLE_SYSTEM_INFO_T)
#define MDrv_MAD_GET_DSP_CLK                                 _IOR(MAD_IOC_MAGIC, 58, int)
#define MDrv_MAD_SET_DACOUT_VOLUME                                 _IOW(MAD_IOC_MAGIC, 59, int)
#define MDrv_MAD_DELETE_AUDIO_CLIP                                _IOR(MAD_IOC_MAGIC, 60, int)
#define MDrv_MAD_LOAD_AUDIO_CLIP                                _IOW(MAD_IOC_MAGIC, 61, int)
#define MDrv_MAD_PLAY_AUDIO_CLIP                                 _IOW(MAD_IOC_MAGIC, 62, int)
#define MDrv_MAD_PAUSE_AUDIO_CLIP                                 _IO(MAD_IOC_MAGIC, 63)
#define MDrv_MAD_RESUME_AUDIO_CLIP                                 _IO(MAD_IOC_MAGIC, 64)
#define MDrv_MAD_STOP_AUDIO_CLIP                                 _IO(MAD_IOC_MAGIC, 65)
#define MDrv_MAD_GET_HDMI_SYNTH_FREQ                                _IOR(MAD_IOC_MAGIC, 66, int)

#define MDrv_MAD_SIF_GET_SOUND_STANDARD			                            _IOWR(MAD_IOC_MAGIC,67, int)
#define MDrv_MAD_SIF_ACCESS_THRESHOLD					_IOWR(MAD_IOC_MAGIC, 68, AVAILABLE_SYSTEM_INFO_T)
#define MDrv_MAD_SIF_SET_PRESCALE					_IOW(MAD_IOC_MAGIC, 69, ADEC_SIF_SET_PRESCALE_T)
#define MDrv_MAD_GET_EVENT                                _IOR(MAD_IOC_MAGIC, 70, int)
#define MDrv_MAD_SPDIF_SETMODE                                 _IOW(MAD_IOC_MAGIC, 71, int)
#define MDrv_MAD_HDMI_PCM_NONPCM_SET                   _IOW(MAD_IOC_MAGIC, 72, int)
#define MDrv_MAD_GET_HDMI_MONITOR                                   _IOR(MAD_IOC_MAGIC, 73, int)
#define MDrv_MAD_WR_REG_MASK                                     _IOW(MAD_IOC_MAGIC, 74, int)
#define MDrv_MAD_GET_FILE_INFO                                 _IOR(MAD_IOC_MAGIC, 75, int)
#define MDrv_MAD_FILE_SET_INPUT                                 _IOW(MAD_IOC_MAGIC, 76, int)
#define MDrv_MAD_FILE_END_NOTIFICATION                                 _IOW(MAD_IOC_MAGIC, 77, int)
#define MDrv_MAD_FILE_CHECK_PLAYDONE                                 _IOR(MAD_IOC_MAGIC, 78, int)
#define MDrv_MAD_FILE_CHECK_COPY_RQT                                 _IOR(MAD_IOC_MAGIC, 79, int)
#define MDrv_MAD_AUDIO_MPEG_INFO                                 _IOR(MAD_IOC_MAGIC, 80, int)
#define MDrv_MAD_DSP_ALIVE_CHECK                                 _IOR(MAD_IOC_MAGIC, 81, int)
#define MDrv_MAD_FILE_GET_FRAME_NUM                                 _IOR(MAD_IOC_MAGIC, 82, int)

#define MDrv_MAD_PCM_START_UPLOAD                              _IOW(MAD_IOC_MAGIC, 83, int)
#define MDrv_MAD_PCM_STOP_UPLOAD                                _IO(MAD_IOC_MAGIC, 84)
#define MDrv_MAD_PCM_START_DOWNLOAD                         _IOW(MAD_IOC_MAGIC, 85, int)
#define MDrv_MAD_PCM_STOP_DOWNLOAD                           _IO(MAD_IOC_MAGIC, 86)
#define MDrv_MAD_GET_BT_INFO                                         _IOW(MAD_IOC_MAGIC, 87, int)
#define MDrv_MAD_READTIMESTAMP                                    _IOR(MAD_IOC_MAGIC, 88, int)
#define MDrv_MAD_SET_DOLBY_DRC_MODE                          _IOW(MAD_IOC_MAGIC, 89, int)
#define MDrv_MAD_SET_DOLBY_DOWNMIX_MODE                 _IOW(MAD_IOC_MAGIC, 90, int)
#define MDrv_MAD_HDMI_DOLBYMONITOR                            _IOR(MAD_IOC_MAGIC, 91, int)
#define MDrv_MAD_DTV_HDMI_CFG_ 				    	    _IOW(MAD_IOC_MAGIC, 92, int)
#define MDrv_MAD_AC3DEC_DIS  				                  _IOW(MAD_IOC_MAGIC, 93, int)
#define MDrv_MAD_WMA_GETSAMPLERATE 				    _IOR(MAD_IOC_MAGIC, 94, int)
#define MDrv_MAD_WMA_GETBITRATE  				    _IOR(MAD_IOC_MAGIC, 95, int)
#define MDrv_MAD_AAC_GETSAMPLERATE 				    _IOR(MAD_IOC_MAGIC, 97, int)
#define MDrv_MAD_GET_DSP_CODETYPE 				    _IOR(MAD_IOC_MAGIC, 98, int)
#define MDrv_MAD_AUDIO_AC3_INFO                                 _IOR(MAD_IOC_MAGIC, 99, int)
#define MDrv_MAD_AUDIO_HEAAC_INFO                                 _IOR(MAD_IOC_MAGIC, 100, int)
#define MDrv_MAD_RD_DEC_REG                                           _IOWR(MAD_IOC_MAGIC, 101, int)
#define MDrv_MAD_RD_SE_REG                                             _IOWR(MAD_IOC_MAGIC, 102, int)
#define MDrv_MAD_WR_DEC_REG                                          _IOW(MAD_IOC_MAGIC, 103, int)
#define MDrv_MAD_WR_SE_REG                                            _IOW(MAD_IOC_MAGIC, 104, int)
#define MDrv_MAD_DVB_SETFREERUN                                   _IOW(MAD_IOC_MAGIC, 105, int)
#define MDrv_MAD_DVB2_SETFREERUN                                 _IOW(MAD_IOC_MAGIC, 106, int)
#define MDrv_MAD_DVB_XPCM_SETPARAM                           _IOW(MAD_IOC_MAGIC, 107, int)
#define MDrv_MAD_DVB2_SETDECCMD                                 _IOW(MAD_IOC_MAGIC, 108, int)
#define MDrv_MAD_START_DVB2_DECODING				  _IOW(MAD_IOC_MAGIC, 109, int)
#define MDrv_MAD_SET_AD_MUTE                                       _IOW(MAD_IOC_MAGIC, 110, int)
#define MDrv_MAD_GET_MAD_BASE                                       _IOR(MAD_IOC_MAGIC, 111, int)
#define MDrv_MAD_CV3_SET_CV_ENABLE                                 _IOW(MAD_IOC_MAGIC, 112, int)
#define MDrv_MAD_CV3_SET_VOLUME                                  _IOW(MAD_IOC_MAGIC, 113, int)
#define MDrv_MAD_CV3_SET_UEQ                                          _IOW(MAD_IOC_MAGIC, 114, int)
#define MDrv_MAD_MONITOR_SPDIF_NONPCM_FS_RATE         _IO(MAD_IOC_MAGIC, 115)
#define MDrv_MAD_HDMI_AC3_PATHCFG           _IOW(MAD_IOC_MAGIC, 116, int)
#define MDrv_MAD_SET_CV3_PARAM                                     _IOW(MAD_IOC_MAGIC, 117, int)
#define MDrv_MAD_DVB_RA8_SETPARAM                           _IOW(MAD_IOC_MAGIC, 118, int)
#define MDrv_MAD_SOUND_EFFECT_ONOFF                         _IOW(MAD_IOC_MAGIC, 119, int)
#define MDrv_MAD_SIF_CHECKA2DK                              _IOWR(MAD_IOC_MAGIC, 120, AVAILABLE_SYSTEM_INFO_T)
#define MDrv_MAD_SIF_SET_HDEVMODE                _IOW(MAD_IOC_MAGIC, 121, int)
#define MDrv_MAD_SET_DTV_NORMALPATH              _IO(MAD_IOC_MAGIC, 122)
#define MDrv_MAD_SET_ATV_NORMALPATH              _IO(MAD_IOC_MAGIC, 123)
#define MDrv_MAD_SET_DOLBY_AD_DRC_MODE                          _IOW(MAD_IOC_MAGIC, 124, int)
#define MDrv_MAD_POWER_ON_MELODY                    _IO(MAD_IOC_MAGIC, 125)
#define MDrv_MAD_MPEG_SET_FILE_SIZE                 _IOW(MAD_IOC_MAGIC, 126, int)
#define MDrv_MAD_POWER_ON_MELODY_PATH                    _IOW(MAD_IOC_MAGIC, 127, int)
#define MDrv_MAD_ADEC_ALIVE_CHECK                    _IOR(MAD_IOC_MAGIC, 128, int)
#define MDrv_MAD_ASND_ALIVE_CHECK                    _IOR(MAD_IOC_MAGIC, 129, int)
#define MDrv_MAD_ADEC_ES_CHECK                    _IOR(MAD_IOC_MAGIC, 130, int)
#define MDrv_MAD_SET_SRS_DC                          _IOW(MAD_IOC_MAGIC, 131, int)
#define MDrv_MAD_SET_SRS_TRU_BASS               _IOW(MAD_IOC_MAGIC, 132, int)
#define MDrv_MAD_SET_SRS_PARA                       _IOW(MAD_IOC_MAGIC, 133, int)
#define MDrv_MAD_AUPROCESS_WRITE_PARAMETER     _IOW(MAD_IOC_MAGIC, 134, int)
#define MDrv_MAD_SET_SRS_PARA32     _IOW(MAD_IOC_MAGIC, 135, int)
#define MDrv_MAD_GET_DSP2_CODETYPE 				    _IOR(MAD_IOC_MAGIC, 136, int)
#define MDrv_MAD_DVBRPT_DTVES 				    _IOR(MAD_IOC_MAGIC, 137, int)

#define MDrv_MAD_RD_DEC_REGBYTE                                           _IOWR(MAD_IOC_MAGIC, 138, int)
#define MDrv_MAD_WR_DEC_REGBYTE                                          _IOW(MAD_IOC_MAGIC, 139, int)
#define MDrv_MAD_RD_SE_REGBYTE                                           _IOWR(MAD_IOC_MAGIC, 140, int)
#define MDrv_MAD_WR_DEC_MASK_REG                                     _IOW(MAD_IOC_MAGIC, 141, int)
#define MDrv_MAD_WR_SE_MASK_REG                                     _IOW(MAD_IOC_MAGIC, 142, int)
#define MDrv_MAD_WR_DEC_MASK_REGBYTE                                     _IOW(MAD_IOC_MAGIC, 143, int)
#define MDrv_MAD_WR_DEC_MASK_INTBYTE                                     _IOW(MAD_IOC_MAGIC, 144, int)
#define MDrv_MAD_WR_SE_MASK_REGBYTE                                     _IOW(MAD_IOC_MAGIC, 145, int)
#define MDrv_MAD_SET_SPDIF_VOLUME                                     _IOW(MAD_IOC_MAGIC, 146, int)
#define MDrv_MAD_CHECK_AUDIO_ES                                            _IOR(MAD_IOC_MAGIC, 147, int)
#define MDrv_MAD_CV3_PVC_MONITOR                                         _IOR(MAD_IOC_MAGIC, 148, int)
#define MDrv_MAD_AUDIO_MONITOR                                     _IO(MAD_IOC_MAGIC, 149)
#define MDrv_MAD_GET_DEC_DSP_REVIVE_COUNT               _IOR(MAD_IOC_MAGIC, 150, int)
#define MDrv_MAD_MPEG_SET_SOUND_MODE                       _IOW(MAD_IOC_MAGIC, 151, int)
#define MDrv_MAD_MPEG_GET_SOUND_MODE                       _IOR(MAD_IOC_MAGIC, 152, int)
#define MDrv_MAD_DVB2_PLAY_BT                      _IOW(MAD_IOC_MAGIC, 153, int)
#define MDrv_MAD_WR_SE_REGBYTE                                     _IOW(MAD_IOC_MAGIC, 154, int)
#define MDrv_MAD_DVB_PCM_LEVEL_CONTROL         _IOW(MAD_IOC_MAGIC, 155, int)
#define MDrv_MAD_GET_AUDIOSTREAM_INFO             		_IOWR(MAD_IOC_MAGIC, 161, int)
#define MDrv_MAD_SET_AUDIOSTREAM_INPUT                                 _IOW(MAD_IOC_MAGIC, 162, int)
#define MDrv_MAD_PIO8_SE                                                         _IO(MAD_IOC_MAGIC, 163)
#define MDrv_MAD_SPDIF_SETSCMS                                 _IOW(MAD_IOC_MAGIC, 164, int)
#define MDrv_MAD_SPDIF_GETSCMS                                _IOR(MAD_IOC_MAGIC, 165, int)
#define MDrv_MAD_SET_INPUT_PATH                                     _IOW(MAD_IOC_MAGIC, 166, int)
#define MDrv_MAD_SET_COMMAND                                  _IOW(MAD_IOC_MAGIC, 167, int)
#define MDrv_MAD_GET_ENCODE_DONE_FLAG                  _IOR(MAD_IOC_MAGIC, 168, int)
#define MDrv_MAD_START_ENCODING                               _IO(MAD_IOC_MAGIC, 169)
#define MDrv_MAD_STOP_ENCODING                                _IO(MAD_IOC_MAGIC, 170)
#define MDrv_MAD_CLR_ENCODE_DONE_FLAG                  _IO(MAD_IOC_MAGIC, 171)
#define MDrv_MAD_GET_ENCODE_FRAME_INFO                 _IOR(MAD_IOC_MAGIC, 172, int)
#define MDrv_MAD_GET_ENCODE_BUF_INFO                     _IOR(MAD_IOC_MAGIC, 173, int)
#define MDrv_MAD_SET_INTERNAL_PATH                                     _IOW(MAD_IOC_MAGIC, 174, int)
#define MDrv_MAD_SET_WMA_PARAM                                     _IOW(MAD_IOC_MAGIC, 175, int)

#define MDrv_MAD_CV3_SET_AVL2                                          _IOW(MAD_IOC_MAGIC, 176, int)
#define MDrv_MAD_CV3_SET_CV                                          _IOW(MAD_IOC_MAGIC, 177, int)
#define MDrv_MAD_CV3_SET_SURROUND                             _IOW(MAD_IOC_MAGIC, 178, int)

#define MDrv_MAD_DVB2_XPCM_SETPARAM                           _IOW(MAD_IOC_MAGIC, 179, int)
#define MDrv_MAD_GET_FILE_INFO_SE                                 _IOR(MAD_IOC_MAGIC, 180, int)
#define MDrv_MAD_FILE_CHECK_PLAYDONE_SE                                 _IOR(MAD_IOC_MAGIC, 181, int)
#define MDrv_MAD_FILE_END_NOTIFICATION_SE                                 _IOW(MAD_IOC_MAGIC, 182, int)
#define MDrv_MAD_FILE_SET_INPUT_SE                                 _IOW(MAD_IOC_MAGIC, 183, int)
#define MDrv_MAD_CV3_SET_MODE                                  _IOW(MAD_IOC_MAGIC, 184, int)
#define MDrv_MAD_CV3_SET_AVL2_ENABLE                                 _IOW(MAD_IOC_MAGIC, 185, int)
#define MDrv_MAD_CV3_SET_SURROUND_ENABLE                                 _IOW(MAD_IOC_MAGIC, 186, int)
#define MDrv_MAD_CV3_SET_UEQ_ENABLE                                 _IOW(MAD_IOC_MAGIC, 187, int)
#define MDrv_MAD_READTIMESTAMP_SE                                    _IOW(MAD_IOC_MAGIC, 188, int)
//Mstar add for Skype, 2009/09/22
#define MDrv_MAD_INIT_SKYPE                                    _IOW(MAD_IOC_MAGIC, 189, int)
#define MDrv_MAD_SKYPE_DN_PCM                                   _IO(MAD_IOC_MAGIC, 190)
#define MDrv_MAD_STOP_SKYPE                                   _IO(MAD_IOC_MAGIC, 191)
//-------------------------------
#define MDrv_MAD_SIF_ADC_RESET                              _IO(MAD_IOC_MAGIC, 192)
#define MDrv_MAD_CV3_SET_BASS_ENHANCE               _IOW(MAD_IOC_MAGIC, 193, int)
#define MDrv_MAD_SET_CUT_BOOST                             _IOW(MAD_IOC_MAGIC, 194, int)
#define MDrv_MAD_GET_DDP_AD_STATUS                        _IOR(MAD_IOC_MAGIC, 195, int)
#define MDrv_MAD_SET_SPDIF_DELAY_TIME                    _IOW(MAD_IOC_MAGIC, 196, int)
#define MDrv_MAD_SET_DDP_AD_MODE                               _IOW(MAD_IOC_MAGIC, 197, int)
#define MDrv_MAD_GET_PTS                                          _IOR(MAD_IOC_MAGIC, 198, int)
#define MDrv_MAD_SET_ADC_THRESHOLD                    _IOW(MAD_IOC_MAGIC, 199, int)
#define MDrv_MAD_GET_PCM_ENERGY                          _IOR(MAD_IOC_MAGIC, 200, int)
#define MDrv_MAD_RESTORE_VOL                          _IO(MAD_IOC_MAGIC, 201)

#define MDrv_MAD_IOC_MAXNR              205
#if 0
/*
 * S means "Set" through a ptr,
 * T means "Tell" directly with the argument value
 * G means "Get": reply by setting through a pointer
 * Q means "Query": response is on the return value
 * X means "eXchange": switch G and S atomically
 * H means "sHift": switch T and Q atomically
 */
#define SCULL_IOCSQUANTUM _IOW(SCULL_IOC_MAGIC,  1, int)
#define SCULL_IOCSQSET    _IOW(SCULL_IOC_MAGIC,  2, int)
#define SCULL_IOCTQUANTUM _IO(SCULL_IOC_MAGIC,   3)
#define SCULL_IOCTQSET    _IO(SCULL_IOC_MAGIC,   4)
#define SCULL_IOCGQUANTUM _IOR(SCULL_IOC_MAGIC,  5, int)
#define SCULL_IOCGQSET    _IOR(SCULL_IOC_MAGIC,  6, int)
#define SCULL_IOCQQUANTUM _IO(SCULL_IOC_MAGIC,   7)
#define SCULL_IOCQQSET    _IO(SCULL_IOC_MAGIC,   8)
#define SCULL_IOCXQUANTUM _IOWR(SCULL_IOC_MAGIC, 9, int)
#define SCULL_IOCXQSET    _IOWR(SCULL_IOC_MAGIC,10, int)
#define SCULL_IOCHQUANTUM _IO(SCULL_IOC_MAGIC,  11)
#define SCULL_IOCHQSET    _IO(SCULL_IOC_MAGIC,  12)
#endif
