
#ifndef _MDRV_BDMA_ST_H_
#define _MDRV_BDMA_ST_H_

#include "mdrv_types.h"


typedef enum BDMA_DEVICE_e
{
    E_BDMA_DEV_MIU0,
    E_BDMA_DEV_MIU1,
    E_BDMA_DEV_SEARCH,
    E_BDMA_DEV_CRC32,
    E_BDMA_DEV_MEM_FILL,
    E_BDMA_DEV_FLASH,
    E_BDMA_DEV_RESERVED,
    E_BDMA_DEV_VDMCU,
    E_BDMA_DEV_DSP,
    E_BDMA_DEV_TSP,
    E_BDMA_DEV_1KSRAM_HK51,
    E_BDMA_DEV_DRAM_AEON,
    E_BDMA_DEV_NOT_SUPPORT,
}BDMA_DEVICE_t;

#define BDMA_SET_CPYTYPE(type, src, dst) type = ((src & 0x0F) | ((dst &0x0F) << 8))
#define BDMA_CPYTYPE_COL \
    BDMA_SET_CPYTYPE(E_BDMA_SDRAM2SDRAM, E_BDMA_DEV_MIU0, E_BDMA_DEV_MIU0) \
    ,BDMA_SET_CPYTYPE(E_BDMA_SDRAM2SDRAM1, E_BDMA_DEV_MIU0, E_BDMA_DEV_MIU1) \
    ,BDMA_SET_CPYTYPE(E_BDMA_SDRAM2VDMCU, E_BDMA_DEV_MIU0, E_BDMA_DEV_VDMCU) \
    ,BDMA_SET_CPYTYPE(E_BDMA_SDRAM2DSP, E_BDMA_DEV_MIU0, E_BDMA_DEV_DSP) \
    ,BDMA_SET_CPYTYPE(E_BDMA_SDRAM2TSP, E_BDMA_DEV_MIU0, E_BDMA_DEV_TSP) \
    ,BDMA_SET_CPYTYPE(E_BDMA_SDRAM2SRAM1K_HK51, E_BDMA_DEV_MIU0, E_BDMA_DEV_1KSRAM_HK51) \
    ,BDMA_SET_CPYTYPE(E_BDMA_SDRAM12SDRAM, E_BDMA_DEV_MIU1, E_BDMA_DEV_MIU0) \
    ,BDMA_SET_CPYTYPE(E_BDMA_SDRAM12SDRAM1, E_BDMA_DEV_MIU1, E_BDMA_DEV_MIU1) \
    ,BDMA_SET_CPYTYPE(E_BDMA_SDRAM12VDMCU, E_BDMA_DEV_MIU1, E_BDMA_DEV_VDMCU) \
    ,BDMA_SET_CPYTYPE(E_BDMA_SDRAM12DSP, E_BDMA_DEV_MIU1, E_BDMA_DEV_DSP) \
    ,BDMA_SET_CPYTYPE(E_BDMA_SDRAM12TSP, E_BDMA_DEV_MIU1, E_BDMA_DEV_TSP) \
    ,BDMA_SET_CPYTYPE(E_BDMA_SDRAM12SRAM1K_HK51, E_BDMA_DEV_MIU1, E_BDMA_DEV_1KSRAM_HK51) \
    ,BDMA_SET_CPYTYPE(E_BDMA_FLASH2SDRAM, E_BDMA_DEV_FLASH, E_BDMA_DEV_MIU0) \
    ,BDMA_SET_CPYTYPE(E_BDMA_FLASH2SDRAM1, E_BDMA_DEV_FLASH, E_BDMA_DEV_MIU1) \
    ,BDMA_SET_CPYTYPE(E_BDMA_FLASH2VDMCU, E_BDMA_DEV_FLASH, E_BDMA_DEV_VDMCU) \
    ,BDMA_SET_CPYTYPE(E_BDMA_FLASH2DSP, E_BDMA_DEV_FLASH, E_BDMA_DEV_DSP) \
    ,BDMA_SET_CPYTYPE(E_BDMA_FLASH2TSP, E_BDMA_DEV_FLASH, E_BDMA_DEV_TSP) \
    ,BDMA_SET_CPYTYPE(E_BDMA_FLASH2SRAMHK51, E_BDMA_DEV_FLASH, E_BDMA_DEV_1KSRAM_HK51) \
    ,BDMA_SET_CPYTYPE(E_BDMA_FLASH2DRAMAEON, E_BDMA_DEV_FLASH, E_BDMA_DEV_DRAM_AEON)

typedef enum BDMA_CPY_TYPE_e
{
    BDMA_CPYTYPE_COL,
    BDMA_CPYTYPE_MAX,
}BDMA_CPY_TYPE_t;

typedef struct BDMA_PARA_s
{
    U32 u32SrcAddr;
    U32 u32DstAddr;
    U32 u32DataSize;
    U32 u32Pattern;
    U32 u32ExcluBit;
    U32 u32RetValue;
    BDMA_CPY_TYPE_t eCpyType;
    U8 u8OpCfg;
} BDMA_PARA_t, *pBDMA_PARA_t;

#endif

