
#ifndef _MDRV_MVD_IO_H_
#define _MDRV_MVD_IO_H_
/* Use 'v' as magic number */
#define MVD_IOC_MAGIC           'v'

#define MVD_IOC_INIT                    _IOW(MVD_IOC_MAGIC, 0, U32)
#define MVD_IOC_PLAY                    _IOR(MVD_IOC_MAGIC, 1,U32)
#define MVD_IOC_PAUSE                   _IO(MVD_IOC_MAGIC, 2)
#define MVD_IOC_STOP                    _IO(MVD_IOC_MAGIC, 3)
#define MVD_IOC_DECODE_IFRAME           _IOW(MVD_IOC_MAGIC, 4, MVD_IFRAME_ADDR)
#define MVD_IOC_GET_FRAME_CNT           _IOR(MVD_IOC_MAGIC, 5, U32)
#define MVD_IOC_GET_PIC_DATA            _IOW(MVD_IOC_MAGIC, 6, MVD_FRAMEINFO)
#define MVD_IOC_RESET                   _IOW(MVD_IOC_MAGIC, 7, U32)
#define MVD_IOC_GET_FIRST_FRAME         _IO(MVD_IOC_MAGIC, 8)
#define MVD_IOC_GET_DISP_RDY            _IO(MVD_IOC_MAGIC, 9)
#define MVD_IOC_GET_SYNC_STATUS         _IO(MVD_IOC_MAGIC, 10)
#define MVD_IOC_SET_VOP_DONE            _IO(MVD_IOC_MAGIC, 11)
#define MVD_IOC_GET_PROG_INTL           _IO(MVD_IOC_MAGIC, 12)
#define MVD_IOC_SET_PWR_ON              _IO(MVD_IOC_MAGIC, 13)
#define MVD_IOC_SET_PWR_OFF             _IO(MVD_IOC_MAGIC, 14)
#define MVD_IOC_GET_ACTIVEFORMAT        _IO(MVD_IOC_MAGIC, 15)
#define MVD_IOC_WAITEVENT               _IOWR(MVD_IOC_MAGIC, 16, MVD_FRAMEINFO)
#define MVD_IOC_CLOSEWAIT		        _IO(MVD_IOC_MAGIC,17)
#define MVD_IOC_TOGGLE_AV_SYNC	        _IOR(MVD_IOC_MAGIC,18, U8)
#define MVD_IOC_REG_INT     	        _IO(MVD_IOC_MAGIC,19)
#define MVD_IOC_DEREG_INT     	        _IO(MVD_IOC_MAGIC,20)
#define MVD_IOC_WAIT_INT_EVENT 	        _IO(MVD_IOC_MAGIC,21)
#define MVD_IOC_GET_AV_SYNC_STATUS      _IOW(MVD_IOC_MAGIC, 22, U32)
#define MVD_IOC_SET_INT_FLAG            _IOR(MVD_IOC_MAGIC, 23, U32)
#define MVD_IOC_SET_FILE_PLAY           _IOWR(MVD_IOC_MAGIC, 24, MVD_BUFFER_INFO)
#define MVD_IOC_SET_FILE_CLOSE          _IO(MVD_IOC_MAGIC, 25)
#define MVD_IOC_SET_FILE_PLAY2          _IOWR(MVD_IOC_MAGIC, 26, MVD_PLAY_MODE_T)
#define MVD_IOC_SET_PVR_MODE            _IOWR(MVD_IOC_MAGIC, 27, MVD_PVR_MODE_T)
#define MVD_IOC_LOCAL_PLAY_INIT         _IOR(MVD_IOC_MAGIC, 28, U32)
#define MVD_IOC_LOCAL_PLAY_CLOSE        _IO(MVD_IOC_MAGIC, 29)
#define MVD_IOC_LOCAL_PLAY_DOWNLOADING  _IO(MVD_IOC_MAGIC, 30)
#define MVD_IOC_LOCAL_PLAY_DOWNLOADEND  _IOR(MVD_IOC_MAGIC, 31, U32)
#define MVD_IOC_CLEAN_BIT_STREAM_BUFF   _IO(MVD_IOC_MAGIC, 32)
#define MVD_IOC_I_PIC_FOUND				_IO(MVD_IOC_MAGIC, 33)
#define MVD_IOC_GET_VIDEO_REPEAT		_IO(MVD_IOC_MAGIC, 34)
#define MVD_IOC_GET_VIDEO_SKIP			_IO(MVD_IOC_MAGIC, 35)
#define MVD_IOC_GET_PTS			   		_IO(MVD_IOC_MAGIC, 36)
#define MVD_IOC_GET_FRAMEBUF            _IOWR(MVD_IOC_MAGIC, 37, MVD_BUFFER_INFO)
#define MVD_IOC_SET_DATA_MEM            _IOWR(MVD_IOC_MAGIC, 38, U32)
#define MVD_IOC_SET_AVSYNC_THRESHOLD    _IOWR(MVD_IOC_MAGIC, 39, U16)
#define MVD_IOC_SET_DELAY				_IOW(MVD_IOC_MAGIC, 40, U32)
#define MVD_IOC_SET_SYNC_THRESHOLD	    _IOW(MVD_IOC_MAGIC, 41, U32)/*jaehoon, added by mstar to improve lipsync */
#define MVD_IOC_SET_PLAY_MODE           _IOW(MVD_IOC_MAGIC, 42, U32)
#define MVD_IOC_STEP_PLAY               _IO(MVD_IOC_MAGIC, 43)
#define MVD_IOC_GET_ESDATASIZE          _IOR(MVD_IOC_MAGIC, 44, U32)
#define MVD_IOC_GET_ESRDPTR             _IOR(MVD_IOC_MAGIC, 45, U32)
#define MVD_IOC_GET_ESWRPTR             _IOR(MVD_IOC_MAGIC, 46, U32)
#define MVD_IOC_SET_SYNCREPEATTH        _IOW(MVD_IOC_MAGIC, 47, U32)
#define MVD_IOC_SET_SKIP_REPEAT_MODE    _IOW(MVD_IOC_MAGIC, 48, U8)

#define MVD_IOC_MAXNR           49

#endif
